name: Build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.6
      - name: Build jar
        run: mvn package -f pom.xml
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Test-Sender
          path: ${{ github.workspace }}/target/TestSender-1.0-SNAPSHOT.jar